### ISSUE TITLE
Missing Lato "500" weight

### ISSUE THREAD

**Issue by enricobasso** [07akioni/vfonts#2]
Hi! Naive UI user here. A lot of Naive components use the var ...-font-weight-500 but since in Lato we have only '400' and '600' font weight you don't get the bold-ish effect using something like `<n-text strong>`. This could be fixed for my use case customizing the theme via the config provider or adding custom css with the desired font weight, but I don't know if providing a solution "out of the box" could benefit more people.
I hope that what I wrote makes sense 😄

**Comment by 07akioni** [comment]
I forget why I didn't config lato as 600. Maybe I found that browser would take the actual font weight regardless of what I set or there would be some display issues when Chinese and Latin characters are mixed together.

However there must be some reasons that made I do so. You are right. The font size must be configured while using Lato. I should document it in Naive UI's doc.

I won't try to make it work out of box, since its implementation won't be clear. (vfonts is pure css and can't easily detected by js)

I choose 500 for naive since for most fonts 500 is enough to distinguish from regular weight. However Lato's 600 looks like many other 500s...

**Comment by enricobasso** [comment]
> I choose 500 for naive since for most fonts 500 is enough to distinguish from regular weight. However Lato's 600 looks like many other 500s...

In fact my workaround was to add this in my css 😄 

```
@font-face {
  font-family: "v-sans";
  font-weight: 500;
  src: url("./assets/LatoLatin-Semibold.woff2");
}
```

It works for me but I don't know if it is ok.

**Comment by 07akioni** [comment]
@enricobasso https://bugs.chromium.org/p/chromium/issues/detail?id=1153370&hotlist_id=5255&sort=%20rank%20-ID

It's becase this reason. For a English only site, your solution should work.

**Comment by enricobasso** [comment]
Oh, now I understand. Well I hope this will get fixed! For what concerns me, I can live with that workaround. As you said maybe a warning in the Naive UI docs could be helpful for future users. 
Thanks for the replies 👍🏻

**Comment by 07akioni** [comment]
See https://www.naiveui.com/en-US/os-theme/docs/fonts for new docs.
